package com.capgemini.service.impl;

import com.capgemini.entity.Courses;
import com.capgemini.entity.Student;
import com.capgemini.entity.dto.StudentRequestDto;
import com.capgemini.entity.dto.StudentResponseDto;
import com.capgemini.repository.StudentRepository;
import com.capgemini.service.StudentService;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class StudentServiceImpl implements StudentService {
    private final StudentRepository studentRepository;
    private final ModelMapper modelMapper;
    @Transactional
    public void enrollStudent(StudentRequestDto studentRequestDto){
        Student s1 = new Student();
        s1.setName(studentRequestDto.getName());
        List<Courses> coursesList = studentRequestDto.getCourses().stream()
                .map(courseName -> {
                    Courses c = new Courses();
                    c.setCourseName(courseName);
                    c.setStudent(s1);
                    return c;
                })
                .collect(Collectors.toList());

        //s1.setId(studentRequestDto.getId());
        s1.setCourses(coursesList);

        studentRepository.save(s1);
    }

    public StudentResponseDto getStudentById(Long id){
        Student student = studentRepository.findStudentByid(id);//findStudentByid is generated by springboot using keywords
        return modelMapper.map(student, StudentResponseDto.class);

    }


    public List<StudentResponseDto> getStudentsByCourse(String course){
        List<Student> students = studentRepository.findStudentsByCourses_CourseName(course);
        return students.stream()
                .map(student -> modelMapper.map(student,StudentResponseDto.class))
                .collect(Collectors.toList());

    }

}
